# Generated by Django 3.2.8 on 2021-10-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.CharField(max_length=20)),
                ('SubCategories', models.CharField(max_length=20)),
                ('Categories', models.CharField(max_length=20)),
            ],
        ),
    ]
